### ISSUE TITLE
Can't compile with "xinput" feature

### ISSUE THREAD

**Issue by yoanlcq** [rust-x-bindings/rust-xcb#52]
Greetings,

I tried to compile a dummy project with the following in my `Cargo.toml` : 
```toml
[dependencies]
xcb = { version = "0.8.1", features = ["glx", "randr", "render", "xinerama", "xinput"] }
```
And this was the stderr output of `cargo check --verbose` (Quite long, but I'd rather not cut parts of it).  
It is the same on stable (1.21) and nightly (1.22).   
But, if I remove the "xinput" feature, it compiles fine.
```txt
       Fresh log v0.3.8
       Fresh libc v0.2.33
   Compiling xcb v0.8.1
     Running `rustc --crate-name xcb /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/lib.rs --crate-type lib --emit=dep-info,metadata -C debuginfo=2 --cfg 'feature="glx"' --cfg 'feature="randr"' --cfg 'feature="render"' --cfg 'feature="shape"' --cfg 'feature="xfixes"' --cfg 'feature="xinerama"' --cfg 'feature="xinput"' -C metadata=7abdd7d3db7ad546 -C extra-filename=-7abdd7d3db7ad546 --out-dir /home/yoon/xcbtoast/target/debug/deps -L dependency=/home/yoon/xcbtoast/target/debug/deps --extern libc=/home/yoon/xcbtoast/target/debug/deps/liblibc-ce722587a4bf678b.rmeta --extern log=/home/yoon/xcbtoast/target/debug/deps/liblog-eb9750e2038c4aae.rmeta --cap-lints allow`
error[E0425]: cannot find function `xcb_input_device_changed_classes_iterator` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8197:13
     |
8197 |             xcb_input_device_changed_classes_iterator(self.ptr)
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `xcb_input_xi_device_info_classes_iterator`?

error[E0425]: cannot find value `num_classes` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8213:34
     |
8213 |             (*raw).num_classes = num_classes;
     |                                  ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `xcb_input_key_press_button_mask_length` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8302:23
     |
8302 |             let len = xcb_input_key_press_button_mask_length(field) as usize;
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `xcb_input_key_press_button_mask` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8303:24
     |
8303 |             let data = xcb_input_key_press_button_mask(field);
     |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `xcb_input_key_press_valuator_mask_length` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8310:23
     |
8310 |             let len = xcb_input_key_press_valuator_mask_length(field) as usize;
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `xcb_input_key_press_valuator_mask` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8311:24
     |
8311 |             let data = xcb_input_key_press_valuator_mask(field);
     |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `buttons_len` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8353:34
     |
8353 |             (*raw).buttons_len = buttons_len;
     |                                  ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `valuators_len` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8354:36
     |
8354 |             (*raw).valuators_len = valuators_len;
     |                                    ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `xcb_input_button_press_button_mask_length` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8450:23
     |
8450 |             let len = xcb_input_button_press_button_mask_length(field) as usize;
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `xcb_input_button_class_state_length`?

error[E0425]: cannot find function `xcb_input_button_press_button_mask` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8451:24
     |
8451 |             let data = xcb_input_button_press_button_mask(field);
     |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `xcb_input_button_press_valuator_mask_length` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8458:23
     |
8458 |             let len = xcb_input_button_press_valuator_mask_length(field) as usize;
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `xcb_input_button_class_labels_length`?

error[E0425]: cannot find function `xcb_input_button_press_valuator_mask` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8459:24
     |
8459 |             let data = xcb_input_button_press_valuator_mask(field);
     |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `buttons_len` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8503:34
     |
8503 |             (*raw).buttons_len = buttons_len;
     |                                  ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `valuators_len` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8504:36
     |
8504 |             (*raw).valuators_len = valuators_len;
     |                                    ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `xcb_input_enter_buttons_length` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8614:23
     |
8614 |             let len = xcb_input_enter_buttons_length(field) as usize;
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `xcb_input_enter_buttons` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8615:24
     |
8615 |             let data = xcb_input_enter_buttons(field);
     |                        ^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `buttons_len` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8666:34
     |
8666 |             (*raw).buttons_len = buttons_len;
     |                                  ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `xcb_input_hierarchy_infos_iterator` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8781:13
     |
8781 |             xcb_input_hierarchy_infos_iterator(self.ptr)
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `xcb_input_hierarchy_info_next`?

error[E0425]: cannot find value `num_infos` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8797:32
     |
8797 |             (*raw).num_infos = num_infos;
     |                                ^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `xcb_input_raw_key_press_valuator_mask_length` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8885:23
     |
8885 |             let len = xcb_input_raw_key_press_valuator_mask_length(field) as usize;
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `xcb_input_raw_key_press_valuator_mask` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8886:24
     |
8886 |             let data = xcb_input_raw_key_press_valuator_mask(field);
     |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `valuators_len` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8912:36
     |
8912 |             (*raw).valuators_len = valuators_len;
     |                                    ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `xcb_input_raw_button_press_valuator_mask_length` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8959:23
     |
8959 |             let len = xcb_input_raw_button_press_valuator_mask_length(field) as usize;
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `xcb_input_valuator_state_valuators_length`?

error[E0425]: cannot find function `xcb_input_raw_button_press_valuator_mask` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8960:24
     |
8960 |             let data = xcb_input_raw_button_press_valuator_mask(field);
     |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `valuators_len` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8988:36
     |
8988 |             (*raw).valuators_len = valuators_len;
     |                                    ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `xcb_input_touch_begin_button_mask_length` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:9084:23
     |
9084 |             let len = xcb_input_touch_begin_button_mask_length(field) as usize;
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `xcb_input_touch_begin_button_mask` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:9085:24
     |
9085 |             let data = xcb_input_touch_begin_button_mask(field);
     |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `xcb_input_touch_begin_valuator_mask_length` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:9092:23
     |
9092 |             let len = xcb_input_touch_begin_valuator_mask_length(field) as usize;
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `xcb_input_touch_begin_valuator_mask` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:9093:24
     |
9093 |             let data = xcb_input_touch_begin_valuator_mask(field);
     |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `buttons_len` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:9137:34
     |
9137 |             (*raw).buttons_len = buttons_len;
     |                                  ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `valuators_len` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:9138:36
     |
9138 |             (*raw).valuators_len = valuators_len;
     |                                    ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `xcb_input_raw_touch_begin_valuator_mask_length` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:9267:23
     |
9267 |             let len = xcb_input_raw_touch_begin_valuator_mask_length(field) as usize;
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `xcb_input_raw_touch_begin_valuator_mask` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:9268:24
     |
9268 |             let data = xcb_input_raw_touch_begin_valuator_mask(field);
     |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `valuators_len` in this scope
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:9296:36
     |
9296 |             (*raw).valuators_len = valuators_len;
     |                                    ^^^^^^^^^^^^^ not found in this scope

error[E0308]: mismatched types
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:3097:56
     |
3097 |                                                        feedback_ptr);  // 3
     |                                                        ^^^^^^^^^^^^ types differ in mutability
     |
     = note: expected type `*mut ffi::input::xcb_input_feedback_ctl_t`
                found type `*const ffi::input::xcb_input_feedback_ctl_t`

error[E0308]: mismatched types
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:3121:64
     |
3121 |                                                                feedback_ptr);  // 3
     |                                                                ^^^^^^^^^^^^ types differ in mutability
     |
     = note: expected type `*mut ffi::input::xcb_input_feedback_ctl_t`
                found type `*const ffi::input::xcb_input_feedback_ctl_t`

error[E0609]: no field `control` on type `ffi::input::xcb_input_get_device_control_reply_t`
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:4410:46
     |
4410 |             std::mem::transmute(&(*self.ptr).control)
     |                                              ^^^^^^^ unknown field
     |
     = note: available fields are: `response_type`, `pad0`, `sequence`, `length`, `status`, `pad1`

error[E0308]: mismatched types
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:4890:54
     |
4890 |                                                      control_ptr);  // 2
     |                                                      ^^^^^^^^^^^ types differ in mutability
     |
     = note: expected type `*mut ffi::input::xcb_input_device_ctl_t`
                found type `*const ffi::input::xcb_input_device_ctl_t`

error[E0308]: mismatched types
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:4912:64
     |
4912 |                                                                control_ptr);  // 2
     |                                                                ^^^^^^^^^^^ types differ in mutability
     |
     = note: expected type `*mut ffi::input::xcb_input_device_ctl_t`
                found type `*const ffi::input::xcb_input_device_ctl_t`

error[E0609]: no field `classes` on type `ffi::input::xcb_input_device_changed_event_t`
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8216:20
     |
8216 |             (*raw).classes = classes;
     |                    ^^^^^^^ unknown field
     |
     = note: available fields are: `response_type`, `extension`, `sequence`, `length`, `event_type` ... and 7 others

error[E0609]: no field `button_mask` on type `ffi::input::xcb_input_key_press_event_t`
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8359:20
     |
8359 |             (*raw).button_mask = button_mask;
     |                    ^^^^^^^^^^^ unknown field
     |
     = note: available fields are: `response_type`, `extension`, `sequence`, `length`, `event_type` ... and 18 others

error[E0609]: no field `valuator_mask` on type `ffi::input::xcb_input_key_press_event_t`
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8360:20
     |
8360 |             (*raw).valuator_mask = valuator_mask;
     |                    ^^^^^^^^^^^^^ unknown field
     |
     = note: available fields are: `response_type`, `extension`, `sequence`, `length`, `event_type` ... and 18 others

error[E0609]: no field `button_mask` on type `ffi::input::xcb_input_button_press_event_t`
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8509:20
     |
8509 |             (*raw).button_mask = button_mask;
     |                    ^^^^^^^^^^^ unknown field
     |
     = note: available fields are: `response_type`, `extension`, `sequence`, `length`, `event_type` ... and 18 others

error[E0609]: no field `valuator_mask` on type `ffi::input::xcb_input_button_press_event_t`
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8510:20
     |
8510 |             (*raw).valuator_mask = valuator_mask;
     |                    ^^^^^^^^^^^^^ unknown field
     |
     = note: available fields are: `response_type`, `extension`, `sequence`, `length`, `event_type` ... and 18 others

error[E0609]: no field `buttons` on type `ffi::input::xcb_input_enter_event_t`
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8669:20
     |
8669 |             (*raw).buttons = buttons;
     |                    ^^^^^^^ unknown field
     |
     = note: available fields are: `response_type`, `extension`, `sequence`, `length`, `event_type` ... and 18 others

error[E0609]: no field `infos` on type `ffi::input::xcb_input_hierarchy_event_t`
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8798:20
     |
8798 |             (*raw).infos = infos;
     |                    ^^^^^ unknown field
     |
     = note: available fields are: `response_type`, `extension`, `sequence`, `length`, `event_type` ... and 6 others

error[E0609]: no field `valuator_mask` on type `ffi::input::xcb_input_raw_key_press_event_t`
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8914:20
     |
8914 |             (*raw).valuator_mask = valuator_mask;
     |                    ^^^^^^^^^^^^^ unknown field
     |
     = note: available fields are: `response_type`, `extension`, `sequence`, `length`, `event_type` ... and 8 others

error[E0609]: no field `valuator_mask` on type `ffi::input::xcb_input_raw_button_press_event_t`
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:8990:20
     |
8990 |             (*raw).valuator_mask = valuator_mask;
     |                    ^^^^^^^^^^^^^ unknown field
     |
     = note: available fields are: `response_type`, `extension`, `sequence`, `length`, `event_type` ... and 8 others

error[E0609]: no field `button_mask` on type `ffi::input::xcb_input_touch_begin_event_t`
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:9143:20
     |
9143 |             (*raw).button_mask = button_mask;
     |                    ^^^^^^^^^^^ unknown field
     |
     = note: available fields are: `response_type`, `extension`, `sequence`, `length`, `event_type` ... and 18 others

error[E0609]: no field `valuator_mask` on type `ffi::input::xcb_input_touch_begin_event_t`
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:9144:20
     |
9144 |             (*raw).valuator_mask = valuator_mask;
     |                    ^^^^^^^^^^^^^ unknown field
     |
     = note: available fields are: `response_type`, `extension`, `sequence`, `length`, `event_type` ... and 18 others

error[E0609]: no field `valuator_mask` on type `ffi::input::xcb_input_raw_touch_begin_event_t`
    --> /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/input.rs:9298:20
     |
9298 |             (*raw).valuator_mask = valuator_mask;
     |                    ^^^^^^^^^^^^^ unknown field
     |
     = note: available fields are: `response_type`, `extension`, `sequence`, `length`, `event_type` ... and 8 others

error: aborting due to 51 previous errors

error: Could not compile `xcb`.

Caused by:
  process didn't exit successfully: `rustc --crate-name xcb /home/yoon/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.8.1/src/lib.rs --crate-type lib --emit=dep-info,metadata -C debuginfo=2 --cfg feature="glx" --cfg feature="randr" --cfg feature="render" --cfg feature="shape" --cfg feature="xfixes" --cfg feature="xinerama" --cfg feature="xinput" -C metadata=7abdd7d3db7ad546 -C extra-filename=-7abdd7d3db7ad546 --out-dir /home/yoon/xcbtoast/target/debug/deps -L dependency=/home/yoon/xcbtoast/target/debug/deps --extern libc=/home/yoon/xcbtoast/target/debug/deps/liblibc-ce722587a4bf678b.rmeta --extern log=/home/yoon/xcbtoast/target/debug/deps/liblog-eb9750e2038c4aae.rmeta --cap-lints allow` (exit code: 101)

```

**Comment by rtbo** [comment]
Xinput does not work at the moment, there's a pull-request to address this: #33

**Comment by andrewshadura** [comment]
I’ve also run into this :confused:

**Comment by rtbo** [comment]
Xinput works in `v1.0` (currently beta).
See https://github.com/rust-x-bindings/rust-xcb/blob/v1.0-dev/examples/xinput_stylus_events.rs

**Comment by andrewshadura** [comment]
Too late, I have switched to x11rb already 🙂

**Comment by rtbo** [comment]
Nearly two years later, I can't blame you! :smile:

**Comment by rtbo** [comment]
[v1.0.0](https://crates.io/crates/xcb/1.0.0) is released.
