### ISSUE TITLE
Example does not compile

### ISSUE THREAD

**Issue by Maxzor** [rust-x-bindings/rust-xcb#122]
Hello and thank you for the library.
If I understood correctly v1 beta is not a wraper anymore but a proper implementation?

[This example](https://github.com/rust-x-bindings/rust-xcb/blob/v1.0-dev/examples/basic_window.rs) does not compile. Rust 1.56.1 here.

```
error[E0308]: mismatched types
  --> src/main.rs:37:30
   |
37 |             x::Cw::EventMask(x::EventMask::EXPOSURE | x::EventMask::KEY_PRESS)
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found struct `xcb::x::EventMask`
```

I am only at rust book chapter 8 so I won't be able to help solving this type mismatch today :)

**Comment by Maxzor** [comment]
You could put examples on CI?

**Comment by rtbo** [comment]
Hi and thank you for testing the beta!
The example does compile on the `v1.0-dev` branch and they are checked in CI through `cargo test --all-features`.
It doesn't compile for you because I have fixed some problems in the API since the release of the `beta.0`.
You may either test directly the branch tip, or use the examples as they were released at the `beta-0` stage.
See [here](https://github.com/rust-x-bindings/rust-xcb/blob/a865d188dce3f4f88d0158ff7d677e9ca3f063e0/examples/basic_window.rs).
In this case you have to change to 
```rust
    x::Cw::EventMask((x::EventMask::EXPOSURE | x::EventMask::KEY_PRESS).bits())
```
(`Cw::EventMask` used to take `u32` but has been fixed to accept a `x::EventMask`)

I will release `beta.1`. It will be easier!

**Comment by Maxzor** [comment]
Got the idea of using bits too, but the struct fields were not public.
Ty for quick feedback!

**Comment by Maxzor** [comment]
Thank you for the quick feedback!

**Comment by rtbo** [comment]
`v1.0.0-beta.1` is on [crates.io](https://crates.io/crates/xcb/1.0.0-beta.1).

**Comment by rtbo** [comment]
@Maxzor as for your initial question, in `v1` the `Connection` class is still a binding struct to the `xcb_connection_t` C struct and associated functions, but the protocol requests and events are now proper implementation in Rust. 

This means, I don't bind anymore to functions such as `xcb_create_window`, I have instead a request struct `x::CreateWindow` that serializes itself to raw bytes as expected by XCB. This very similar as what `xcb_create_window` does. 

See [here](https://rust-x-bindings.github.io/rust-xcb/branches/v1.0-dev/src/xcb/home/runner/work/rust-xcb/rust-xcb/target/debug/build/xcb-83607561d8e551f0/out/xproto.rs.html#10491) if you are curious about how it works.

For events, the methods are accessors over the raw data received from the server.
